### ISSUE TITLE
Project submission - OHBM Hackathon (June 16th-18th 2020)

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-matlab#100]
## Project info
The **shimming-toolbox** is open-source Matlab software enabling a variety of MRI shimming (magnetic field homogenization) techniques for use with custom "multi-coil" arrays or standard manufacturer-supplied hardware.
This project was initiated by the NeuroPoly Lab (Polytechnique Montréal) in collaboration with the Martinos Center for Biomedical Imaging (Harvard Medical School).

**Title**:
shimming-toolbox: Ecosystem for real-time shimming with MRI

**Project lead**:
- Julien Cohen-Adad @jcohenadad,
- Ryan Topfer @rtopfer 
- Alexandre D'Astous @po09i 
- Gaspard Cereza @gaspardcereza 
- Eva Alonso-Ortiz @evaalonsoortiz
- Jason Stockmann @jaystock

**[Timezone](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#timezone)**:
UTC-5

**Hub**:
The Americas

**Description**:
A prerequisite to correcting/shimming the MR "b0" field is of course to measure it (commonly done using a dual-echo gradient-echo sequence). A recent paper by [Fatnassi and Zaidi](https://iopscience.iop.org/article/10.1088/1361-6560/aae570 ) suggests that multi-echo (n>2) sequences may yield better accuracy and higher SNR. This *brainhack* project aims to implement multi-echo field mapping algorithms and assess their efficiency.

**Link to project**:
[shimming-toolbox repository](https://github.com/shimming-toolbox/shimming-toolbox)
[shimming-toolbox website](http://www.shimming-toolbox.org/)

**Mattermost handle**:
[shimming-toolbox channel](https://mattermost.brainhack.org/brainhack/channels/shimming-toolbox)

**Goals for the OHBM Brainhack**
Implement B0 field mapping algorithms for more than 2 echoes
- Selective weighted field-mapping ([SWFM](https://iopscience.iop.org/article/10.1088/1361-6560/aae570 ))
- Linear least square fit (LLSf) 

**Good first issues**:
- [Create numerical model data for multi-echo field maps](https://github.com/shimming-toolbox/shimming-toolbox/issues/102)
- [Implement a complex division (CD) algorithm using 2 echoes](https://github.com/shimming-toolbox/shimming-toolbox/issues/112)

**Skills**:
- Matlab coding
- MR physics (mapping, phase unwrapping)
 
**Chat channel**:
[shimming-toolbox Mattermost channel](https://mattermost.brainhack.org/brainhack/channels/shimming-toolbox)

**Video channel**:
[shimming-toolbox Jitsi channel](https://meet.jit.si/shimming-toolbox-hackathon)

## Additional project info

**Acknowledgments**
Members contributing will be listed [here](https://github.com/shimming-toolbox/shimming-toolbox/graphs/contributors) 

**Links**
Link to [Fatnassi and Zaidi](https://iopscience.iop.org/article/10.1088/1361-6560/aae570 )

## Submission checklist
*Once the issue is submitted, please check items in this list as you add under 'Additional project info'*

Please include the following above (all required):
-   [x] Link to your project: could be a code repository, a shared document, etc. See [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#link-to-project)
-   [x] Include your Mattermost handle. If you do not have an account, please [sign up here](https://mattermost.brainhack.org/signup_email).
-   [x] Goals for the OHBM Brainhack: describe what you want to achieve during this brainhack. See [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#goals).
-   [x] Flesh out at least 2 "good first issues": those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document, cf [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#onboarding-2-good-first-issues).
-   [x] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill, cf. [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#onboarding-skills).
-   [x] Chat channel: A link to a chat channel that will be used during the OHBM Brainhack. This can be an existing channel or a new one. We recommend using the [Brainhack space on mattermost](https://mattermost.brainhack.org/), cf. [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#chat).
-   [x] Video channel: Please create a video channel that will be used during the OHBM Brainhack and share it in your chat channel above. This can be an existing channel or a new one. For instance a [jitsi meet](https://meet.jit.si/) room, cf. [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#video-calls).

You can also include information about (all optional):
-   [ ] Number of participants, cf. [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#participant-capacity)
-   [ ] Twitter-size summary of your project pitch, cf. [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#twitter-size-summary-of-your-project-pitch)
-   [ ] Provide an image of your project for the OHBM brainhack website
-   [x] Set up a kanban board on your repository to better divide the work and keep track of things, cf [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#set-up-a-kanban-board)
-   [ ] Project snippet for the OHBM Brainhack website, cf. [here](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#project-snippet-for-the-ohbm-brainhack-website)

We would like to think about how you will credit and onboard new members to your project. We recommend reading references from [this section](https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md#credit-and-onboarding). If you'd like to share your thoughts with future project participants, you can include information about (recommended):
-   [x] Specify how will you acknowledge contributions (e.g. listing members on a contributing page).
-   [ ] Provide links to onboarding documents if you have some.

**Comment by gaspardcereza** [comment]
Here's a draft of the project submission because we couldn't edit [Julien's post](https://github.com/ohbm/hackathon2020/issues/128) on the hackathon's repo. Feel free to give ideas and edit.

**Comment by jcohenadad** [comment]
>  we couldn't edit Julien's post on the hackathon's repo

too bad-- let's finalize this today so i can update the issue on the brainhack website. Ping me when finalized

**Comment by gaspardcereza** [comment]
> > we couldn't edit Julien's post on the hackathon's repo
> 
> too bad-- let's finalize this today so i can update the issue on the brainhack website. Ping me when finalized

We still haven't defined the precise goals of the project. We planned to think about it and define the final goals tomorrow during our 2pm code meeting. Is it ok for you if we finalize all that tomorrow ?

**Comment by Remi-Gau** [comment]
Let me know if anything is unclear with the project submission process for the hackathon. Happy to help. :-)

**Comment by jcohenadad** [comment]
@rtopfer @po09i can you please define these acronyms: SWFM, LLSf (sorry no time to google...)

**Comment by po09i** [comment]
@jcohenadad The project submission can be copied on the hackathon page. The link was posted on the first comment :

> Here's a draft of the project submission because we couldn't edit [Julien's post](https://github.com/ohbm/hackathon2020/issues/128) on the hackathon's repo. Feel free to give ideas and edit.

The steps for submission are as follow, step one and two are done so we can proceed with step 3.

> *We have prepared a checklist to help with your project submission. Here is how to proceed:*
> 1. *Before filling in any part, please submit this issue*
> 2. *Check items in the checklist below as you go through them*
> 3. *Once you are done (at least all 'required' items must be provided), please delete the >"Guidelines" section add a comment saying 'hi @ohbm/project-monitors: My project is ready!'*

**Comment by jcohenadad** [comment]
updated!
