### ISSUE TITLE
Implement multi-echo B0 mapping algorithms

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-matlab#101]
We assume that multi-echo B0 mapping is a potential way of obtaining better B0 maps compared to classic dual-echo methods. 
Here are some algorithms that could be implemented: 
- Selective Weighted Field Mapping (SWFM)
- Linear Least Square fit (LLSf) 
More info: [Fatnassi 2018](https://pubmed.ncbi.nlm.nih.gov/30272567/)

This issue stands as a one of the starting points for the OHBM 2020 BrainHack Hackathon.

**Comment by jcohenadad** [comment]
@this is not a "good first issue" but an overarching goal for a 3-day hackathon

**Comment by gaspardcereza** [comment]
> @this is not a "good first issue" but an overarching goal for a 3-day hackathon

Our idea was to compare different algorithms to find the one that could be the most efficient for our B0 mapping. That's why we thought that one of the first thing to do was to implement different algorithms. We also see this as a way to understand how the B0 mapping works.

**Comment by jcohenadad** [comment]
sure, but a "good first issue" is supposed to be [beginner-friendly](https://help.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#finding-good-first-issues). Implementing a B0 mapping algorithm is not something a first-year bachelor student in CS or physics would be able to do. It (i) requires extensive understanding of MR physics, (ii) describes an "epic" (i.e. not a few lines of code) new feature. 

An example of good-first-issue would be: create a function that takes a 4D nifti as input and outputs an array with the following dimensions: (X, Y, Z, time, echo number).

What you need to do is break down the "epic" task into smaller tasks, some of which being candidates for a good first issue.

**Comment by evaalonsoortiz** [comment]
Should we close this issue now that it has been broken down into smaller bits?

**Comment by gaspardcereza** [comment]
Done
