### ISSUE TITLE
Create numerical model data for multi-echo field maps

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox-matlab#102]
Add the ability to generate nifti multi-echo fieldmap data.
- The data should include magnitude and phase for more than 2 echoes.
- The data should include wraps. 
- The output should be a nifti file containing the data stored as (x,y,z,time,echo) as well as a matlab vector containing the data. (the time component can be 1 for now)

**Comment by mathieuboudreau** [comment]
I can maybe contribute to this one. B0 maps is likely the quantitative technique that I'm less familiar with, so I might need some "supervision" to make sure I don't stray off too much.

**Comment by mathieuboudreau** [comment]
Is it ok to do this simulation in 2D to start off with? Or is 3D preferred?

I had a Shepp-Logan code setup for some T1 compressed sensing during my PhD that I could reuse, but it was in 2D: https://github.com/mathieuboudreau/Sparse-VFA-T1-by-OMP/blob/master/utils/createModSheppLoganBrainTissueT1Phantom.m

There's some 3D ones available too online: https://www.mathworks.com/matlabcentral/fileexchange/9416-3d-shepp-logan-phantom

**Comment by mathieuboudreau** [comment]
I created this branch for myself: [mb/numerical_model](https://github.com/shimming-toolbox/shimming-toolbox/tree/mb/numerical_model)

**Comment by po09i** [comment]
Notes from @rtopfer :
- magnitude (signal) follows a known model of exp. decay ([Eq. 1](www.ajnr.org/content/30/1/19))
- phase (signal) increases linearly w/echo time
- phase SNR ≅ mag SNR
- mag noise distribution is approx. Gaussian

**Comment by mathieuboudreau** [comment]
Great, thanks!

I've created a basic class + tests in [mb/numerical_model](https://github.com/shimming-toolbox/shimming-toolbox/tree/mb/numerical_model)

My string of ideas would be to do something of the following:

* [x] Create basic starting volume upon class initialisation (e.g. 2D Shepp-Logan)
  * [x] Assign properties for different "classes" of tissue (e.g. T2)
* [x] Define property or methods to keep track of the volume after changes are made to it (i.e. volume vs starting volume).
* [x] Add class method to add noise to the volume.
  * [x] Against which "tissue" should SNR be defined for?
  * [x] Needs to add noise to the real and imaginary parts, so that it propogates to the phase.
  * [x] Noise should be applied after the echo times.
* [x] Define a background B0 field shape and strength
  * [x] Linear? Gaussian?
* [x] Add method to calculate the "signals" after the input echo times
* [x] Save to nifti

Each of these steps should have tests.

**Comment by rtopfer** [comment]
(Note edited "[Eq. 1](www.ajnr.org/content/30/1/19)" in above comment to link to the intended article from Haacke et al.)

**Comment by evaalonsoortiz** [comment]
I don't see any reason why 2D wouldn't be OK. We acquire 2D field maps for our applications often enough that we have methods for analyzing/unwrapping them.

**Comment by mathieuboudreau** [comment]
What's the difference between the `time` and `echo` parameters `data` from the original comment in the issue?

**Comment by mathieuboudreau** [comment]
I just realized that since this isn't clear to me, maybe I didn't fully understand the initial problem

**Comment by evaalonsoortiz** [comment]
We often acquire a time series of field maps. I will edit the original description to try to make it clearer.

**Comment by evaalonsoortiz** [comment]
Ok, I started to edit the description and realized that I too am confused. We often acquire a time series of dual-echo data to generate a time series of field maps. Looking [here](https://brainder.org/2012/09/23/the-nifti-file-format/) I see that the nifti format dimensions should be: x,y,z,t, with t being time, which is usually understood to be the echo time. There are 3 additional dimensions that can be used. So, I would think that if we want to save a time series as a single nifti file the fifth dimension would be the _acquisition number in the series_. So, the reverse of what is in the original comment. @rtopfer @po09i @jcohenadad What do you all think? Is there a reason we went with this order (x,y,z,time,echo)?

**Comment by po09i** [comment]
@evaalonsoortiz I understood t as being acquisition number and not echoes and discussed with Ryan and Gaspard about what format we should use, we concluded on acquisition number but I am open to change again if the normal format is (x,y,z,echo,acqNumber) (only experiment.m and load_niftis would change).

**Comment by jcohenadad** [comment]
I’m ok with `(x, y, z, echoTime, acqNumber) `, or better:  `(x, y, z, echoTime, acqTime) `, so all dimensions are in physical units (otherwise we need to keep a hand on the TR to convert acqNumber in seconds

**Comment by evaalonsoortiz** [comment]
I no one objects, I would like to go with `(x, y, z, echoTime, acqTime) ` . Can anyone confirm that fsleyes would open such an image?

**Comment by jcohenadad** [comment]
ok, i misread the main goal [here](https://github.com/shimming-toolbox/shimming-toolbox/issues/102#issue-632737303). I thought we were talking about the matlab array organization (i.e. matlab variable, not nifti file). Question: why do we absolutely need to have everything inside a single nifti file? 

I guess this is a more general question about our workflow: 
- do we want to deal with single 5D nifti files (knowing FSLeyes doesn't deal well with visualizing 5D files, we need to convert them to tensors, etc. a bit of a pain)
- do we want to deal with multiple 4D (x,y,z,echoTime) files?

i would favor the latter.

related question: in our 2D (x,y) fieldmap protocol with repetition (multiple acqTime), are we creating multiple files (one per acqTime) or a single file (x, y, 1, echo, acqTime)? @rtopfer @po09i

**Comment by po09i** [comment]
@jcohenadad You were right the first time, we are talking here about how to represent the data under Matlab which makes sense to store an acquisition under one 5d variable, I think the general community assumes this order (x,y,z,echoNumber, acquisitionNumber) which is what we want to go forward with. We can discuss how to store the matlab vector in a seperate issue?

> do we want to deal with multiple 4D (x,y,z,echoTime) files?

Going this route also means it is consistent if we output niftis

> I’m ok with `(x, y, z, echoTime, acqNumber) `, or better: `(x, y, z, echoTime, acqTime) `, so all dimensions are in physical units (otherwise we need to keep a hand on the TR to convert acqNumber in seconds

Matlab does not support non integer indexing so I would suggest going with (x,y,z,echoNumber, acquisitionNumber).

**Comment by evaalonsoortiz** [comment]
For the matlab data structure: 5D is fine and we can go ahead with `(x, y, z, echoTime, acqTime)` Note that the index of the 5th dimension is the acquisition number and the variable that is stored is the acquisition time. Likewise for the 4th dimension. 

For saving nifti's: If we try to stick to the [BIDS convention](https://bep001.readthedocs.io/en/dev/04-modality-specific-files/01-magnetic-resonance-imaging-data.html), looking at the section on T1-weighted images it seems that each acquisition would go in a separate image with a label "run" to denote the acquisition. Each nifti then would have 4 dimensions (x,y,z,t), with t being the echos.

**Comment by rtopfer** [comment]
> Matlab does not support non integer indexing so I would suggest going with (x,y,z,echoNumber, acquisitionNumber).

Note: it doesn't support it for generic numeric arrays, but we could instead deal with images straightforwardly as a different type:
- [`map.Containers`](https://www.mathworks.com/help/matlab/map-containers.html) or, 
- define a basic image class and overload the [assignment operators](https://www.mathworks.com/help/matlab/ref/subsasgn.html).
