### ISSUE TITLE
Hackathon: propose Twitter-size summary of your project pitch

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#103]
this is important for visibility

**Comment by po09i** [comment]
Neuropoly’s shimming-toolbox team participates in OHBM Brainhack Hackathon. This year’s project aims to implement multi-echo field mapping algorithms and assess their efficiency.
https://github.com/shimming-toolbox
@PolyNeuro
#OHBMHackathon #Brainhack #OHBM2020

**Comment by po09i** [comment]
@jcohenadad Can you update the [hackathon post](https://github.com/ohbm/hackathon2020/issues/128) with :

**Twitter project pitch**
Neuropoly’s shimming-toolbox team participates in OHBM Brainhack Hackathon. This year’s project aims to implement multi-echo field mapping algorithms and assess their efficiency.
https://github.com/shimming-toolbox
@PolyNeuro
#OHBMHackathon #Brainhack #OHBM2020

**Comment by jcohenadad** [comment]
done 😊
