### ISSUE TITLE
Hackathon:  Provide an image of your project for the OHBM brainhack website

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#104]
important for visibility + it was specifically asked for: https://github.com/ohbm/hackathon2020/issues/128#issuecomment-640140605

**Comment by po09i** [comment]
Could provide shimming-toolbox's logo once it is finished in #109

**Comment by gaspardcereza** [comment]
I provided the logo [here](https://github.com/ohbm/hackathon2020/issues/128#issue-631072476)

**Comment by gaspardcereza** [comment]
Our logo is now displayed on the hackathon's website.
