### ISSUE TITLE
 Specify how will you acknowledge contributions (e.g. listing members on a contributing page).

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#107]

**Comment by evaalonsoortiz** [comment]
Any contributors will automatically be listed [here](https://github.com/shimming-toolbox/shimming-toolbox/graphs/contributors), right? We can state that.

**Comment by po09i** [comment]
Added in the [hackathon post](https://github.com/ohbm/hackathon2020/issues/128)
