### ISSUE TITLE
Create logo for project

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#109]
My suggestion is to create an editable gslide, have the team propose designs, and then submit to large crowd vote via gform.

**Comment by rtopfer** [comment]
Rough sketch (tuning fork + dipole field). *Please* someone w/more graphic design skill do something with either concept!

![shimming-toolbox-logo_RT_v0](https://user-images.githubusercontent.com/3819344/83973416-34b3ce00-a8b4-11ea-8b47-4508da55642b.png)

**Comment by jcohenadad** [comment]
happy to "tune" this logo (i would try without the horizontal grey line). What format is that in? if you could put the source on the gdrive it would be awesome

**Comment by gaspardcereza** [comment]
Final logo: 
![shimming_toolbox_logo](https://user-images.githubusercontent.com/54723104/84316426-1d394700-ab39-11ea-910e-bf60721c0b30.png)

**Comment by jcohenadad** [comment]
no, issues should be closed via a PR (which will be reviewed by the team). The PR should include the logo in the repository.

**Comment by jcohenadad** [comment]
typically, logos go under `docs/img/`, so in our case it would go under the shimming-toolbox.org repos (again, another incentive to merge the two repos... this is getting **very** confusing).
