### ISSUE TITLE
Implement a complex division (CD) algorithm using 2 echoes

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-matlab#112]
B0 maps are conventionally generated using a dual echo (aka: complex division) technique, where the difference in phase, ∆φ, between two images acquired at different echo times (TE1 and TE2) is divided by the echo spacing, ∆TE (where  ∆TE = TE2-TE1):

∆B0 =∆φ/(γ∆TE) 							       

∆φ can be obtained using the four-quadrant arctangent function [1] of the complex phase difference or of the Hermitian inner product. 

This B0 mapping technique will serve as a reference for other B0 mapping methods that will be implemented  (issues #117 and #116). We have already implemented a [version](https://github.com/shimming-toolbox/shimming-toolbox/blob/199b4045c9dfed1343dbbc578e51a4f5c385c1f5/Img/FieldEval.m#L739) of this algorithm that will need to be adapted to accept Nifti files using [read_nii.m](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/%2Bimutils/read_nii.m)

Note: read_nii will switch the time and echo dimensions with respect to the data structure used in our [previous implementation](https://github.com/shimming-toolbox/shimming-toolbox/blob/199b4045c9dfed1343dbbc578e51a4f5c385c1f5/Img/FieldEval.m#L739). 

[1] Bernstein, M.A., K.F. King, and X.J. Zhou, Handbook of MRI pulse sequences. 2004, Academic Press: Amsterdam ; Boston. p. 1 online resource (xxii, 1017 p.).

**Comment by tashrifbillah** [comment]
> that will need to be adapted to accept Nifti files using read_nii.m

What file format does it accept now?

**Comment by gaspardcereza** [comment]
Hi Tashrif, thanks for showing interest in our work !
Until now we were dealing with `DICOM` files as it is quickly explained [here](https://github.com/shimming-toolbox/shimming-toolbox/blob/199b4045c9dfed1343dbbc578e51a4f5c385c1f5/Img/FieldEval.m#L739). We recently decided to go with `NIFTI` files because they are compatible with many applications and have many  other handy features. The idea here is basically to replace the old function we had by a new function that reads the 'NIFTI' files and does the same calculation as before. You can generate the NIFTI files by running the 'example/experiment.m' function (once you have installed all the required applications).

Edit: @mathieuboudreau is currently trying to implement a way to modelise 'NIFTI' files that you could potentially use as input once they're available.

**Comment by tashrifbillah** [comment]
Can we chat on Zoom?

**Comment by po09i** [comment]
Would jitsi work for you? We are currently in a call and you can join. The link is on the general info of the [kanban](https://github.com/shimming-toolbox/shimming-toolbox/projects/3).

**Comment by tashrifbillah** [comment]
Don't see any link neither any text "kanban".

**Comment by po09i** [comment]
[Video link](https://meet.jit.si/shimming-toolbox-hackathon)

**Comment by evaalonsoortiz** [comment]
I am closing this issue because it was addressed in PR #163
