### ISSUE TITLE
Prepare example file for hackathon 

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#115]
- from videotape branch:
  - clean experiment.m
  - add instructions about where is the call to fieldmap generation
  - move this file to: examples/experiment.m
- merge videotape branch
- complete instructions on project "general information and resources/Getting started": https://github.com/shimming-toolbox/shimming-toolbox/projects/3

**Comment by po09i** [comment]
@gaspardcereza just merged the videotape branch, can you update the "general information and resources/Getting started"

**Comment by po09i** [comment]
this can be closed as it was done.
