### ISSUE TITLE
Implement the Linear Least Square fit algorithm (LLSf)

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-matlab#117]
The magnetic (B0) field can be measured from a series of gradient echo (GRE) images through a linear least squares regression of the phase of the GRE images vs. the echo times (TEs) [1]. Phase wraps can be removed by adding or subtracting 2π whenever the phase across successive TEs differs by more than π. 

LLSf-based B0 mapping has been implemented [here](https://github.com/evaalonsoortiz/LLSf_B0mapping). This code can be used as a starting point for integrating this approach within the shimming-toolbox. 

[1] Reber, P.J., et al., Correction of off resonance-related distortion in echo-planar imaging using EPI-based field maps. Magn Reson Med, 1998. 39(2): p. 328-30.

**Comment by evaalonsoortiz** [comment]
I will add a link to some scripts once I get permission from other contributing authors.
