### ISSUE TITLE
Algorithm ideas for B0 fieldmaps

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox-matlab#120]
List of things that we can implement during the hackathon.

[Linear Least Square fit algorithm (LLSf)](https://github.com/evaalonsoortiz/LLSf_B0mapping)
[Selective Weighted Field Mapping (SWFM)](https://pubmed.ncbi.nlm.nih.gov/30272567/)
[UMPIRE](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4062430/)

Spatial Phase unwrapping
- Sunwrap
- wrapper to Prelude
- SEGUE
- QGU

**Comment by evaalonsoortiz** [comment]
What's the goal of this issue? To have an exhaustive list of B0 mapping methods? If so I can add more. For the phase unwrapping algorithms I would put that into a separate issue. Is the goal there to have participants in the hackathon potentially re-implement some of these phase unwrapping methods within the new nifti framework?

**Comment by po09i** [comment]
My goal is to have a list of things that we can implement during the hackathon.

**Comment by mathieuboudreau** [comment]
FYI: The FSL license doesn't allow for reproducing the code, so if you want to write up a PRELUDE algorithm I don't think you can "look under the hood" too much: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence

I don't think there's anything preventing you from reading the PRELUDE paper (https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.10354) and writing up your own algorithm from scratch though - you just can't copy what's done in FSL (which is what's officially called PRELUDE).

**Comment by mathieuboudreau** [comment]
We had a whole discussion about our experience playing with a few different B0 map algorithms  in the qMRLab repo: https://github.com/qMRLab/qMRLab/issues/48

**Comment by evaalonsoortiz** [comment]
Yes, we should be clear that we are looking to write wrappers to some of these functions (such as prelude).

**Comment by evaalonsoortiz** [comment]
> We had a whole discussion about our experience playing with a few different B0 map algorithms in the qMRLab repo: [qMRLab/qMRLab#48](https://github.com/qMRLab/qMRLab/issues/48)

Thanks for the link! Lots of valuable discussions in there.

**Comment by evaalonsoortiz** [comment]
> My goal is to have a list of things that we can implement during the hackathon.

I think that the General info section in the kanban board is the best place for a *wishlist* like this. Then for the individual items, an individual issue with more descriptions.

**Comment by po09i** [comment]
That makes sense, I can put the items in a wishlist in the Kanban board.

**Comment by po09i** [comment]
Can close, moved to Kanban board description.
