### ISSUE TITLE
dcm2niix doesn't separate magnitude and phase with B1 mapping dicoms

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-matlab#121]
When I run it on RF mapping dicoms (standard or rf-maps acquisitions), dcm2niix gathers all the dicoms into one nifti file.
I think that might be related to the fact that these dicoms doesn't have the exact same fields as the others we play with (e.g. no ImageType field). By default, the phase and magnitudes are thus stored in the same nifti. 

The dicoms I used are standard RF maps from the MNI measurements (also available on duke/mri/mni-7t):
[MNI_STANDARD.zip](https://github.com/shimming-toolbox/shimming-toolbox/files/4787550/MNI_STANDARD.zip)

The easiest way to call the function from the command prompt is to go in the folder where the data have been extracted and type: `dcm2niix MNI_STANDARD`

I did it on Windows 10 64-bits with dcm2niix v1.0.20200331 (the latest version)

**Comment by jcohenadad** [comment]
@gaspardcereza if the data are <10MB, it is better to upload them here because:
- duke is internal access
- easier to just click and download
- uploading a zip file is immutable (whereas a link is not-- which might hamper reproducibility in the future)

**Comment by jcohenadad** [comment]
also, always a good habit to put the exact syntax you used:
- more time efficient for the person reproducing your issue,
- better reproducibility (in case you used flags, etc.)

**Comment by gaspardcereza** [comment]
Issue moved [here](https://github.com/shimming-toolbox/shimming-toolbox-py/issues/58).
