### ISSUE TITLE
Implement a simple B0 mapping function

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-matlab#128]
This function is required for testing purpose related to #102. 
It should allow the user to easily compute B0 fielmaps from magnitude and phase 5D arrays (x, y, z, nEchos, nAcquisitions) and from the header containing the echo times (read from the json file).

**Comment by jcohenadad** [comment]
> This function is required for testing purpose related to #102.

i think this function will not only be used for testing purpose, but also as a function that should be exposed to the user for calculating B0 fieldmaps, as it is already the case with the [FieldEval](https://github.com/shimming-toolbox/shimming-toolbox/blob/f320602c07c97216176daaee3ebf8ca0542368da/Img/FieldEval.m#L744) function, which I believe will be refactored at some point

**Comment by evaalonsoortiz** [comment]
I am closing this issue because it has been addressed in PR #163 which is now merged with master
