### ISSUE TITLE
Remove the trigger of Azure pipeline's website generation from PRs

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox-matlab#135]
Currently, the website gets built on every push to a PR whose branch was created after June 17th (need to have the azure-pipelines.yml file in the branch). This should be changed so that only the master branch gets built. 

The best solution would be on a merge to master but since azure is built for CI, this might not be available. Other options include scheduled triggers (at noon everyday) and manual triggers before closing a PR (/AzurePipelines run).

**Comment by gaspardcereza** [comment]
If we choose the schedule triggers, is it still possible to trigger it manually at any moment ?If so I think it's a better solution than relying only on manual triggers.

**Comment by po09i** [comment]
> If we choose the schedule triggers, is it still possible to trigger it manually at any moment ?If so I think it's a better solution than relying only on manual triggers.

I'm confident the manual runs would also trigger the build of the website although not 100% sure. Would have to make sure.

**Comment by po09i** [comment]
Here is a dummy azure-pipelines.yml that would trigger master once a day

```
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
```

**Comment by jcohenadad** [comment]
Daily build seems reasonable to me

**Comment by po09i** [comment]
I figured out that triggers are different than PR triggers. Triggers are when a change to a branch is done and PR triggers are done when there is a change to a PR. It is possible to know which trigger started the build at runtime so we can check that the trigger was on a change to master and only update the website in that case.

By default, all changes to PRs will trigger a build.
