### ISSUE TITLE
Real time filter of capacitive probe output

### ISSUE THREAD

**Issue by alexfoias** [shimming-toolbox/shimming-toolbox-matlab#14]
Complete description of the problem [here](https://docs.google.com/document/d/1TXaYTfHYrfTIfu60gRR-6B_dla-Ja4RMTo_o7mJaNeg/edit).

Let's use this thread to follow code implementation

**Comment by alexfoias** [comment]
a WIP here: https://github.com/neuropoly/realtime_shimming/blob/alfoi/CapacitiveProbe/RespiratoryProbe/filter_CapacitiveProbe.m

I tried to filter & fit polynomial on a sliding window, but the real time result is always biased (upward or downward depending on the moment in time).

Detection of 0 in the filtered signal (signal - polyfit) doesn't seem to work in the current implementation since the signal values are  not always 0. The plot is an interpolation of the values.

**Comment by jcohenadad** [comment]
> Detection of 0 in the filtered signal (signal - polyfit) doesn't seem to work in the current implementation since the signal values are always 0

How come the filtered signal values are always 0? when you do "signal minus polyfit", you should obtain a sine function which mean is zero, not a flat line, right?

**Comment by alexfoias** [comment]
Sorry for the mistake. What i wanted to say is that the values are not exactly 0 and the plot is an interpolation of the values.

**Comment by Aureliengilliot** [comment]
If we multiply the values from t and t-1 and search for negative answers then we could find the place where the signal sign changes ? But it's not really precise ?

**Comment by jcohenadad** [comment]
>  But it's not really precise

it will be precise enough for our application
