### ISSUE TITLE
CI and doc build

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#143]
Currently, we have:
- MoxUnits launched by GH actions, launched for each PR
- Azure pipeline for testing and building doc, launched for each PR + merge on master

ideally, we should centralize CI and doc build in Azure, having:
- one pipeline for CI, which runs for new PRs and merge to master
- another pipeline for building docs, which runs for every new merge to master

moreover, @mathieuboudreau has started to deploy unit testing scripts using `runTestSuite()` here https://github.com/shimming-toolbox/shimming-toolbox/pull/127, so i suggest we move to this testing framework (and get rid of MoxUnits, which was initially deployed having Octave compatibility in mind)

**Comment by po09i** [comment]
I actually [fixed](https://github.com/shimming-toolbox/shimming-toolbox/pull/136) part of this yesterday, we have 2 azure pipelines:
- [One](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/azure-pipelines.yml) for the doc generation that runs on every merge to master
- [One](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/tests/azure-pipelines.yml) pipeline that runs a a dummy matlab command on every PR and merge to master

What is left to do is remove the MoxUnits and set up the matlab unitTests in the azurePipelines YAML file.

**Comment by jcohenadad** [comment]
@po09i I understand this is now implemented, right? Can this issue be closed?

**Comment by po09i** [comment]
Not yet, this [PR](https://github.com/shimming-toolbox/shimming-toolbox/pull/149) will close the issue.
