### ISSUE TITLE
Expand the capabilities of NumericalModel.m 

### ISSUE THREAD

**Issue by evaalonsoortiz** [shimming-toolbox/shimming-toolbox-matlab#151]
NumericalModel.m currently allows the user to simulate T2* decay in a 2D Shepp-Logan phantom using matlab's `phantom` function. A linear B0 gradient can be added to simulate T2* decay in an inhomogeneous B0 field. 

The capabilities of NumericalModel.m should be expanded so that T2* decay is simulated 

- for phantoms of other shapes that will eventually be used in-vivo; such as spherical and cylindrical phantoms

- in the presence of an arbitrary deltaB0 distribution (that can be supplied by the user)

**Comment by mathieuboudreau** [comment]
Cool! Happy to provide input or assistance if any part of the design of this class is not clear or needs to be refactored for this extended functionality to work.
