### ISSUE TITLE
Reference to non-existent field 'probeType'

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#19]
plugging capacitive sensor on my laptop, then running this:
~~~
>> P = ProbeTracking();
Reference to non-existent field 'probeType'.

Error in ProbeTracking.declareprobe (line 966)
    switch AuxSpecs.probeType

Error in ProbeTracking (line 126)
    [ Aux.Source, Aux.Specs ] = ProbeTracking.declareprobe( Specs ) ;
~~~

things should probably get configured under `/dev` but this needs documentation (hence this issue)

**Comment by jcohenadad** [comment]
Related to these lines:
https://github.com/neuropoly/realtime_shimming/blob/alfoi/CapacitiveProbe/RespiratoryProbe/ProbeTracking.m#L958

Things could probably be improved there to be station-agnostic

**Comment by rtopfer** [comment]
I'm not sure what you mean by configuring things under /dev. Indeed, a user needs to determine how each device is identified by their specific computer and USB port, then add the appropriate strings to that switch/case structure following the lines you've referenced.
A slightly more elegant solution is what I suggested in the [documentation](https://github.com/neuropoly/realtime_shimming/blob/bb2970c50747f18541179556636afb933d362f5a/RespiratoryProbe/ProbeTracking.m#L13)
Ideally, the Arduino/Teensy device ID could just be configured by us to be station independent, but I don't think that is easily done.

**Comment by jcohenadad** [comment]
teensys have generic IDs (i think), the present code was too restrictive (station-dependent), i've made it more flexible, see https://github.com/neuropoly/realtime_shimming/pull/15
