### ISSUE TITLE
Enable retrospective calculation of Siemens gradients

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#22]
Input: 
- fieldmap
- siemens PMU resp trace

output:
- variable with info

ideally: would output text file.

**Comment by jcohenadad** [comment]
@evaalonsoortiz it is a good habit to comment the reason for closing an issue. In this case I assume the reason is that it is already implemented in [this example](https://github.com/neuropoly/realtime_shimming/blob/master/example/demozshim.m)?

**Comment by evaalonsoortiz** [comment]
@jcohenadad Ah, I see! 

This issue has been closed because the requested feature is now implemented within [example/realtime_zshim.m](https://github.com/neuropoly/realtime_shimming/blob/master/example/realtime_zshim.m)
