### ISSUE TITLE
Add a method to ShimOpt that reveals the available channel names

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#29]
add a method to ShimOpt that reveals the available channel names and thus the input order for the Params.activeXChannelsMask terms, e.g. ShimOpt.getactivechannels()

More info in this [discussion thread](https://github.com/neuropoly/realtime_shimming/pull/26#issuecomment-528104360)

**Comment by rtopfer** [comment]
[Commit](https://github.com/neuropoly/realtime_shimming/commit/f862eb1accdb864085e524c6a64ff6f69159eaee) added method _tableshim()_ to ShimOpt.m:
Any ShimOpt-type object Shim can call Shim.tableshim(), which returns a table wherein the 1st column are the channel names/shim terms, and the 2nd column lists their current settings (entries in Shim.System.currents). 
(Note: Shim.System.currents are all zeroes unless it is 1) updated manually by the user, 2) for ShimOpt_IUGM_Prisma_fit, when Shim.setoriginalfield( Field ) is called (and it is called within the constructor if Field is given as an input) then the shim coefficients used to acquire Field are extracted from the DICOM header and copied to Shim.System.currents)
