### ISSUE TITLE
Enable dynamic (slicewise) Z-shimming

### ISSUE THREAD

**Issue by rtopfer** [shimming-toolbox/shimming-toolbox-matlab#35]

**Comment by evaalonsoortiz** [comment]
@rtopfer please review 
@rtopfer and @jcohenadad  please add your segmentation and resampling modifications to this script

**Comment by jcohenadad** [comment]
> @rtopfer please review
> @rtopfer and @jcohenadad please add your segmentation and resampling modifications to this script

here is the script mentioned in the quote above:
https://github.com/neuropoly/realtime_shimming/blob/039ffa8ed2056ed9e92eba90cdaa71693f3689a7/example/dynaminc_zshim.m
