### ISSUE TITLE
Implement API and user documentation

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#37]
The project would benefit from a documentation, which is comprehensive and does not require heavy maintenance. There would be two levels of documentation: user-focused (big picture explanation, examples, pictures, etc.) and API documentation.

A few features needed:
- generation of static html should be automated (e.g. done by readthedocs)
- documentation would be hosted on separate page, and nicely formatted (e.g., readthedocs, github-page)

Matlab probably has mechanisms to generate documentation. Let's list various options in this issue:
- API-documentation with sphinx for Matlab (**the** way to go): https://sphinxcontrib-matlabdomain.readthedocs.io/en/latest/
  - example: https://canlabcore.readthedocs.io/en/latest/
- https://stackoverflow.com/questions/26242145/what-is-the-mathworks-way-to-generate-matlab-html-documentation
- https://www.mathworks.com/matlabcentral/fileexchange/25925-using-doxygen-with-matlab
- example: https://quantiacs-matlab-toolbox-documentation.readthedocs.io/en/latest/#

**Comment by po09i** [comment]
When using sphinx to document, can't auto document classes due to a bug when getting attributes : sphinx-doc/sphinx/issues/904

**Comment by po09i** [comment]
Fixed the previously mentioned issue by generating an already working sphinx documentation project (CanlabCore), then running our project. It now works well.

**Comment by rtopfer** [comment]
Working prototype migrated to [new repo](https://github.com/shimming-toolbox/helpDocMd)
