### ISSUE TITLE
Considering merging shimming-toolbox.org and shimming-toolbox

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-matlab#96]
Currently, I see more pros than cons for merging those 2 repos. 
Cons:
- Enables to merge the contributors graphs generated by github
- No need to oscillate between two repos
- Some discussions get spread out between the two repos, making it difficult to track/organize

**Comment by po09i** [comment]
I also see more pros than cons. However, it does provide a layer of organization by splitting the documentation from the development.

**Comment by po09i** [comment]
Pro : Less work/catching up when someone new joins the team

**Comment by jcohenadad** [comment]
@po09i what is the status of this?

**Comment by po09i** [comment]
Everything in the shimming-toolbox.org repo has been closed or transferred to this repo. Once the shimming-toolbox.org repo gets closed, this issue can be closed.

**Comment by jcohenadad** [comment]
https://github.com/shimming-toolbox/shimming-toolbox.org was archived (just in case...)
